spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: circles
    password: as7654321
    driver-class-name: com.mysql.cj.jdbc.Driver

  resources:
    static-locations: classpath:/public, classpath:/resources, classpath:/static, file:E://fakeServer/book

  servlet:
    multipart:
      max-file-size: 100MB
      enabled: true
      file-size-threshold: 0

  thymeleaf:
    cache: false


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.circles.bookstore.bean

server:
  port: 8082
